### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by danpowell88** [linuxserver/docker-qbittorrent#2]
Trying to run this on unRAID 6.3.5 (Linux 4.9.30-unRAID x86_64) using the settings
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="qbittorrent" --net="bridge" -e TZ="Australia/Brisbane" -e HOST_OS="unRAID" -p 10001:6881/tcp -p 10001:6881/udp -p 10000:8080/tcp -v "/mnt/user/appdata/q":"/config":rw -v "/mnt/user/Warez/Downloads/":"/downloads":rw lsioarmhf/qbittorrent
```
and getting

```
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]

panic: standard_init_linux.go:175: exec user process caused "exec format error"


goroutine 1 [running, locked to thread]:
panic(0x6ee920, 0xc420128620)
/usr/lib64/go1.7.1/go/src/runtime/panic.go:500 +0x1a1
github.com/urfave/cli.HandleAction.func1(0xc42009b750)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x247
panic(0x6ee920, 0xc420128620)
/usr/lib64/go1.7.1/go/src/runtime/panic.go:458 +0x243
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc42009b1a0, 0xc420022048, 0xc42009b240)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x18f
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc4200bc320, 0xaa19a0, 0xc420128620)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
main.glob..func8(0xc42009ea00, 0x0, 0x0)
/tmp/SBo/runc-1.0.0-rc2/main_unix.go:26 +0x66
reflect.Value.call(0x6d97c0, 0x764dc8, 0x13, 0x73787b, 0x4, 0xc42009b710, 0x1, 0x1, 0x4d0928, 0x72d6e0, ...)
/usr/lib64/go1.7.1/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x6d97c0, 0x764dc8, 0x13, 0xc42009b710, 0x1, 0x1, 0x0, 0xc42009b6f0, 0x4d9906)
/usr/lib64/go1.7.1/go/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x6d97c0, 0x764dc8, 0xc42009ea00, 0x0, 0x0)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x1e0
github.com/urfave/cli.Command.Run(0x737a4b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x748eb7, 0x51, 0x0, ...)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xc3b
github.com/urfave/cli.(*App).Run(0xc4200ca000, 0xc420076060, 0x2, 0x2, 0x0, 0x0)
/tmp/SBo/runc-1.0.0-rc2/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x611
main.main()
/tmp/SBo/runc-1.0.0-rc2/main.go:132 +0xb65

```

Docker version of unraid appears to be
`Docker version 1.12.6, build 6b644ec`

any ideas?

**Comment by sparklyballs** [comment]
you're trying to run the armhf version on unraid.

**Comment by danpowell88** [comment]
Sorry new to this, which version should I be running?

**Comment by CHBMB** [comment]
x86 

https://hub.docker.com/r/linuxserver/qbittorrent/

But there are reasons why we haven't released it.  So expect bugs.

**Comment by danpowell88** [comment]
Excellent cheers, got it up and running, was able to download a few torrents without errors so far.
