### ISSUE TITLE
[BUG] Search plugin does not work after updating to 5.0

### ISSUE THREAD

**Issue by KK612** [linuxserver/docker-qbittorrent#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No search plugins are available under the search tab and clicking the install button and input an url still nothing happens 
![7321](https://github.com/user-attachments/assets/4ef51481-40f3-4e7d-9477-dcc920b91c2c)

### Steps To Reproduce

update to v5.0

### Environment

```markdown
- OS:openmediavault
- How docker service was installed:Via offical OMV plugins
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Hong_Kong
      - WEBUI_PORT=8080
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /downloads/qbittorrent:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
```

### Container logs

```bash
Could not parse Nova search engine capabilities, msg:  
Error:  /config/qBittorrent/nova3/engines/tokyotoshokan.py:39: SyntaxWarning: invalid escape sequence '\s'
  self.get_size_regex = re_compile(".*Size:\s+([^ ]*)\s+.*")
/config/qBittorrent/nova3/engines/tokyotoshokan.py:102: SyntaxWarning: invalid escape sequence '\?'
  additional_links = re_compile("\?lastid=[0-9]+&page=[0-9]+&terms={}".format(query.replace('%20', '\\+')))
/config/qBittorrent/nova3/engines/pornrips.py:25: SyntaxWarning: invalid escape sequence '\d'
  size_pattern = re.compile('(\d+ ?\w+)')
/config/qBittorrent/nova3/engines/magnetdl.py:17: SyntaxWarning: invalid escape sequence '\s'
  '<td\sclass="m"><a\shref="(magnet.*?)"\stitle=".*?class="n"><a\shref="(.*?)"\stitle="(.*?)">.*?<td\sclass="t.">.*?</td><td>.*?</td><td>(.*?)</td><td\sclass="s">(.*?)</td><td\sclass="l">(.*?)</td>')
Traceback (most recent call last):
  File "/config/qBittorrent/nova3/nova2.py", line 266, in <module>
    main(sys.argv[1:])
  File "/config/qBittorrent/nova3/nova2.py", line 224, in main
    displayCapabilities(supported_engines)
  File "/config/qBittorrent/nova3/nova2.py", line 172, in displayCapabilities
    "".join(engines_to_xml(supported_engines)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/qBittorrent/nova3/nova2.py", line 154, in engines_to_xml
    tab, tab, "<name>", search_engine.name, "</name>\n",
                        ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'tokyotoshokan' has no attribute 'name'
Could not parse Nova search engine capabilities, msg:  
Error:  Traceback (most recent call last):
  File "/config/qBittorrent/nova3/nova2.py", line 266, in <module>
    main(sys.argv[1:])
  File "/config/qBittorrent/nova3/nova2.py", line 224, in main
    displayCapabilities(supported_engines)
  File "/config/qBittorrent/nova3/nova2.py", line 172, in displayCapabilities
    "".join(engines_to_xml(supported_engines)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/qBittorrent/nova3/nova2.py", line 154, in engines_to_xml
    tab, tab, "<name>", search_engine.name, "</name>\n",
                        ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'tokyotoshokan' has no attribute 'name'
Catching signal: SIGTERM
Exiting cleanly
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 5.0.1-r0-ls362
Build-date: 2024-11-02T05:49:15+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
WebUI will be started shortly after internal preparations. Please wait...
******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8080
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
[ls.io-init] done.
Could not parse Nova search engine capabilities, msg:  
Error:  Traceback (most recent call last):
  File "/config/qBittorrent/nova3/nova2.py", line 266, in <module>
    main(sys.argv[1:])
  File "/config/qBittorrent/nova3/nova2.py", line 224, in main
    displayCapabilities(supported_engines)
  File "/config/qBittorrent/nova3/nova2.py", line 172, in displayCapabilities
    "".join(engines_to_xml(supported_engines)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/qBittorrent/nova3/nova2.py", line 154, in engines_to_xml
    tab, tab, "<name>", search_engine.name, "</name>\n",
                        ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'tokyotoshokan' has no attribute 'name'
```

**Comment by KK612** [comment]
Problem is solved with a new installation. Just find that the plugin 'Tokyo Toshokan' would break the search plugin system.
